### ISSUE TITLE
Not working for below version 9

### ISSUE THREAD

**Issue by sg-1225** [contactmayankp/BusinessRulesScriptViewer#1]
The plugin does not work for below version 9, I'm getting an error Organisation too old. I wish you can add it to older versions.

**Comment by contactmayankp** [comment]
> you

ok, I will work on changing this soon

**Comment by contactmayankp** [comment]
@sg-1225 please check now, hopefully this should work for CRM 2013

**Comment by sg-1225** [comment]
> @sg-1225 please check now, hopefully this should work for CRM 2013

Works great, thanks again for your wonderful tool.
